---
node:
  address: '0x6DADB33D4Dd6D382f1Ee8C28F52D07841f44eDdB'
  quic_port: 9091
  peers:
    - '/dnsaddr/bootstrap.interfold.network'
  autonetkey: true
  autopassword: true
  dashboard_port: 8082

chains:
  - name: "sepolia"
    rpc_url: "__RPC_URL__"
    contracts:
      interfold:
        address: "0x38A8A686A420023568E995b57B4FBEA371555Ba7"
        deploy_block: 11508431
      ciphernode_registry:
        address: "0xa639b9a7AB05B787fFE258735Cf9541152a0E610"
        deploy_block: 11508403
      bonding_registry:
        address: "0x4b8560271CD78e071f0074f6Db7D344298187F8b"
        deploy_block: 11508404
      slashing_manager:
        address: "0xe9643cdEFfa4a560DBAbB72330aaF923bc46a138"
        deploy_block: 11508400
      fee_token:
        address: "0x1D4b4750A5A2CB04F22979cb3FC05e9Fc51141eA"
        deploy_block: 11508395
      faucet:
        address: "0xCb350D89ACf8FC1720e4BF2cF59B70f30F8D2DbA"
        deploy_block: 11508419
