---
node:
  address: '0x300C4F8Ec26F25363646520075121aD8bB91cfAD'
  quic_port: 9091
  peers:
    - '/dnsaddr/bootstrap-sepolia.interfold.network'
  autonetkey: true
  autopassword: true
  dashboard_port: 8082

chains:
  - name: "sepolia"
    chain_id: 11155111
    rpc_url: "__RPC_URL__"
    contracts:
      interfold:
        address: "0x3E856E24c7a95d0e04d387f847DA6FA9f6F6c20C"
        deploy_block: 11534993
      ciphernode_registry:
        address: "0x374F4542eC634d5437Dd65020781A9D9Df9c2AB8"
        deploy_block: 11534965
      bonding_registry:
        address: "0x90250Dc48CBe109fFaA02AeAFbFBdbF12D7BD4d4"
        deploy_block: 11534966
      slashing_manager:
        address: "0x489FB674B143E48eaCAaC999B3DF9EA6E95eA79f"
        deploy_block: 11534963
      fee_token:
        address: "0xC35B783cA97710be47Fc81D10dADc895EfcD865c"
        deploy_block: 11534960
      faucet:
        address: "0x6e281411C055BEEbD74bDFcB9aB095aa98907F85"
        deploy_block: 11534982
